apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: z-mgkmcache.kb.io
    timeoutSeconds: 30
  - name: z-mclustergkmcache.kb.io
    timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: z-vgkmcache.kb.io
    timeoutSeconds: 30
  - name: z-vclustergkmcache.kb.io
    timeoutSeconds: 30
