apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: z-mgkmcache.kb.io
    reinvocationPolicy: IfNeeded
  - name: z-mclustergkmcache.kb.io
    reinvocationPolicy: IfNeeded
