apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: mgkmcache.kb.io
    timeoutSeconds: 30
    reinvocationPolicy: IfNeeded
  - name: mclustergkmcache.kb.io
    timeoutSeconds: 30
    reinvocationPolicy: IfNeeded
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: vgkmcache.kb.io
    timeoutSeconds: 30
  - name: vclustergkmcache.kb.io
    timeoutSeconds: 30
