apiVersion: tkm.tkm.io/v1alpha1
kind: TritonKernelCache
metadata:
  labels:
    app.kubernetes.io/name: triton-kernel-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: tritonkernelcache-sample
spec:
  # TODO(user): Add fields here
