apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-clustergkmcache-images
spec:
  validationFailureAction: Enforce
  background: true
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-and-mutate-image
      match:
        any:
          - resources:
              kinds:
                - ClusterGKMCache
      verifyImages:
        - imageReferences:
            - "*"
          mutateDigest: true
          attestors:
            - count: 1
              entries:
                - keyless:
                    issuer: https://token.actions.githubusercontent.com
                    subject: https://github.com/*/*
                    rekor:
                      url: https://rekor.sigstore.dev
