apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-gkmcache-images-v3
spec:
  validationFailureAction: Enforce
  background: true
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-v3-bundle-images
      match:
        any:
          - resources:
              kinds:
                - GKMCache
              selector:
                matchLabels:
                  gkm.io/signature-format: cosign-v3
      imageExtractors:
        GKMCache:
          - path: /spec/image
      verifyImages:
        - imageReferences:
            - "*"
          type: SigstoreBundle
          mutateDigest: true
          attestors:
            - count: 1
              entries:
                - keyless:
                    issuer: https://github.com/login/oauth
                    subject: mtahhan@redhat.com
                    rekor:
                      url: https://rekor.sigstore.dev
